[tool.poetry]
name = "pysent"
version = "0.1.0"
description = "Wrapper for sentiment analysis tools"
authors = ["Bartosz Rozek <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
